apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eychatbott1-gitops
  description: This is GitOps manifest for eychatbott1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=eychatbott1
    janus-idp.io/tekton: eychatbott1 
    backstage.io/kubernetes-id: eychatbott1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:default/rhdh 
  lifecycle: experimental
  dependsOn:
    - component:eychatbott1  
