apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-eychatbott1-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-eychatbott1-gitops
    spec:
      serviceAccountName: eychatbott1-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=eychatbott1-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/eychatbott1-notebook -- git clone https://github.com/ai-rolling-demo/echatbottest2
      restartPolicy: Never
