apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: eychatbott1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eychatbott1
  name: eychatbott1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
